name: 'datafactory_$(SourceBranchName)_$(Date:yyyyMMdd)_$(Rev:.r)'
trigger:
  batch: true
  branches:
    include:
      - refs/heads/adf_publish
    exclude:
      - master
      - release
      - develop
pr: none

pool:
  vmImage: 'windows-latest'
stages:
- stage: Build
  displayName: Build
  jobs:
  - job: GenerateArtifacts
    steps:
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact'
      inputs:
        targetPath: ajaytest01
        artifact: ADF
- stage: Deployment
  displayName: Deployment-ADF
  jobs:
  - job: GenerateArtifacts
  steps:
  - task: AzureResourceManagerTemplateDeployment@3
    displayName: 'ARM Template deployment: Resource Group scope'
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: finalservice
      subscriptionId: 'be9a6686-cc74-4a64-aed5-f6c481deec00'
      action: 'Create Or Update Resource Group'
      resourceGroupName: adfkt
      location: WestEurope 
      templateLocation: 'Linked artifact'
      csmFile: $(Agent.BuildDirectory)/ADF/ARMTemplateForFactory.json'
      csmParametersFile: '$(Agent.BuildDirectory)/ADF/QA-ARMTemplateParametersForFactory.json'            
      enabled: false 
      deploymentMode: 'Incremental'
